version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shorty_db
    ports:
      - "3309:3306"
    expose:
      - "3306"
    volumes:
      - ./data/db:/var/lib/mysql
